sourceFiles = Split("""
                       main.cpp
                    """)

Import('env')
recsEnv = env.Clone()

recsEnv.MergeFlags('-O6 -pthread -Wall -Werror')
recsEnv['CXXFLAGS'] = ['-std=c++0x'] # works around bug in scons MergeFlags, fixed in later versions of scons
recsEnv['CPPPATH'] = '#/source'

recs = recsEnv.Program(target = 'recs', source = sourceFiles)
recsInstall = recsEnv.Install('#/bin', recs)

recsEnv.Default(recs)
recsEnv.Default(recsInstall)
