sourceFiles = Split("""
                       main.cpp
                    """)

Import('env')
recsEnv = env.Clone()

recsEnv.MergeFlags('-O6 -pthread -pthread -Wall -Werror')
recsEnv['CXXFLAGS'] = ['-std=c++0x'] # works around bug in scons MergeFlags, fixed in later versions of scons

recs = recsEnv.Program(target = 'recs', source = sourceFiles)
recsEnv.Install('#/bin', recs)

