sourceFiles = Split("""
   src/encodings/compact_lang_det/getonescriptspan.cc
   src/encodings/compact_lang_det/cldutil_dbg_empty.cc
   src/encodings/compact_lang_det/letterscript_enum.cc
   src/encodings/compact_lang_det/ext_lang_enc.cc
   src/encodings/compact_lang_det/cldutil.cc
   src/encodings/compact_lang_det/compact_lang_det.cc
   src/encodings/compact_lang_det/generated/cld_generated_score_quadchrome_0406.cc
   src/encodings/compact_lang_det/generated/compact_lang_det_generated_deltaoctachrome.cc
   src/encodings/compact_lang_det/generated/compact_lang_det_generated_quadschrome.cc
   src/encodings/compact_lang_det/generated/compact_lang_det_generated_cjkbis_0.cc
   src/encodings/compact_lang_det/generated/compact_lang_det_generated_ctjkvz.cc
   src/encodings/compact_lang_det/compact_lang_det_impl.cc
   src/encodings/compact_lang_det/tote.cc
   src/encodings/internal/encodings.cc
   src/languages/internal/languages.cc
                    """)

Import('env')
compactLanguageDetectorEnv = env.Clone()

compactLanguageDetectorEnv.MergeFlags('-O6 -pthread -Wall -Werror -static')
compactLanguageDetectorEnv['CXXFLAGS'] = ['-std=c++0x'] # works around bug in scons MergeFlags, fixed in later versions of scons
compactLanguageDetectorEnv['CPPPATH'] = ['#', '#/lib/compact-language-detector/', '#/lib/compact-language-detector/src']

compactLanguageDetector = compactLanguageDetectorEnv.SharedLibrary(target = 'compact-language-detector', source = sourceFiles)

compactLanguageDetectorEnv.Default(compactLanguageDetector)
